@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
scale 2

class Person {
  +firstname
  +lastname
  -__init__(self, first, last)
  +Name(self)
}

Person <|-- Employee
class Employee {
  +staffnumber
  -__init__(self, first, last, staffnum)
  +GetEmployee(self)
}

@enduml
