@startuml
skinparam monochrome false
skinparam classAttributeIconSize 0
' set namespaceSeparator none
scale 1.2

namespace py2puml {
}
namespace puml_generator {
  class PUML_Generator {
    +dest
    +config
    +sourcename
    -__init__()
    +start_file()
    +end_file()
    +output()
    +header()
    +footer()
    +do_file()
    +print_classinfo()
    +print_codeinfo()
    +arglist()
  }

  PUML_Generator <|-- PUML_Generator_NS
  class PUML_Generator_NS {
    +root
    +namespaces
    -__init__()
    +depth()
    +start_file()
    +pop_ns()
    +push_ns()
    +output()
    +footer()
  }

}
namespace code_info {
  class CodeInfo {
    +variables
    +functions
    -__init__()
    +add_variable()
    +add_function()
    +visibility()
  }

  CodeInfo <|-- ClassInfo
  class ClassInfo {
    +classname
    +bases
    +members
    -__init__()
    +classvars()
    +methods()
    +add_classvar()
    +add_member()
    +add_method()
    +done()
  }

}
namespace ast_visitor {
  ast.NodeVisitor <|-- TreeVisitor
  class TreeVisitor {
    +srcfile
    +context
    +classinfo
    +globals
    +constructor
    +tree
    -__init__()
    +parse()
    +visit_tree()
    +visit_ClassDef()
    +visit_FunctionDef()
    +visit_Assign()
  }

}
@enduml
